config/routes.rb
ShopCart::Engine.routes.draw do
  resources :orders, only: [:index, :show, :update]
  resources :order_items, only: [:index, :destroy, :create] do
    collection do
      delete 'destroy_all', action: 'destroy_all'
      put    'update_all',  action: 'update'
    end
  end

end

app/models/shop_cart/coupon.rb
module ShopCart
  class Coupon < ActiveRecord::Base
    has_many :orders
  end
end

app/models/shop_cart/order.rb
module ShopCart
  class Order < ActiveRecord::Base
    include AASM


    belongs_to :coupon
    belongs_to :customer,         class_name: ShopCart.customer_class
    belongs_to :shipping_address, class_name: ShopCart.address_class,  autosave: true
    belongs_to :billing_address,  class_name: ShopCart.address_class, autosave: true
    belongs_to :delivery_method,  class_name: ShopCart.delivery_class
    belongs_to :credit_card,      class_name: ShopCart.credit_class
    has_many   :order_items

    STATE_IN_PROGRESS = 'in progress'
    scope :already_completed, -> {where.not(state: STATE_IN_PROGRESS)}

    def self.all_completed_orders
      self.already_completed.order(state: :asc, completed_date: :desc)
    end

    validates   :state, presence: true
    enum state: {
             in_progress: "in progress",
             in_queue: "in queue",
             in_delivery: "in delivery",
             delivered: "delivered",
             canceled:  "canceled",
         }
    aasm column: :state, :enum => true do
      state :in_progress, :initial => true
      state :in_queue
      state :in_delivery
      state :delivered
      state :canceled

      event :checkout, :before => :set_completed_date, :after => :update_sold_count do
        transitions :from => :in_progress, :to => :in_queue
      end

      event :confirm do
        transitions :from => :in_queue, :to => :in_delivery
      end

      event :deliver do
        transitions :from => :in_delivery, :to => :delivered
      end

      event :cancel do
        transitions :from => :in_queue, :to => :canceled
      end
    end

    after_create do
      self.update(number: "R"+rand(100000000..999999999).to_s)
    end

    def total_items
      @total_items = self.order_items.sum(:quantity) if @total_items.nil?
      @total_items
    end

    def add_product(product,quantity)
      order = self
      order_item = order.order_items.find_by(:product => product)
      if order_item.nil?
        order_item = OrderItem.new({:product => product, :order => order, :price => product.price, :quantity => quantity})
      else
        order_item.quantity += quantity
      end
      order_item.save
    end

    def total_price
      items_price = self.order_items.map {|item| item.quantity*item.price}
      price = items_price.inject(&:+) || 0
      unless self.coupon.blank?
        self.total_price =  price - self.coupon.price
      else
        self.total_price =  price
      end

    end

    def set_completed_date
      self.completed_date = Time.zone.now
    end

    def products
      self.order_items.includes(:product).references(:product)
    end

    def update_sold_count
      return false if self.state  == STATE_IN_PROGRESS
      self.order_items.each do |order_item|
        ShopCart.product_class.where(id: order_item.product_id).update_all("sold_count = sold_count + #{order_item.quantity}")
      end
    end



  end
end

app/models/shop_cart/order_item.rb
module ShopCart
  class OrderItem < ActiveRecord::Base
    belongs_to :product, class_name: ShopCart.product_class.to_s
    belongs_to :order

    validates :price,:order, :quantity, presence: true

    def find_by_order_id(order)
      self.where(order_id: order)
    end
  end
end

app/controllers/shop_cart/application_controller.rb
module ShopCart
  class ApplicationController < ShopCart.parent_controller.constantize
  end
end

app/controllers/shop_cart/order_items_controller.rb
require_dependency "shop_cart/application_controller"

module ShopCart
  class OrderItemsController < ApplicationController

    before_action :current_order

    def index
      @order_items = @order.order_items
    end

    def destroy_all
      @order.order_items.destroy_all
      flash[:success] = 'Order was successfully destroyed'
      redirect_to :back
    end

    def destroy
      @order.order_items.find(params[:id]).destroy
      flash[:success] = 'One item from order was successfully deleted'
      redirect_to :back
    end

    def create
      book = ShopCart.product_class.find_by_id(order_params[:book_id])
      quantity = order_params[:quantity]
      @order.add_product(book,quantity.to_i)
      flash[:success] = 'Book was successfully added to cart.'
      redirect_to(:back)
    end

    def update
      params[:quantity].each do |item_id, quantity|
        @order.order_items.find_by_id(item_id).update(:quantity => quantity)
      end
      add_coupon unless params[:coupon].blank?
      flash[:success] = 'Order was successfully updated' if flash[:danger].nil?
      redirect_to :back
    end

    private

    def add_coupon
      @coupon = Coupon.find_by(number: params[:coupon])
      if @coupon
        if @order.coupon
          flash[:danger] = 'You already use coupon code'
        else
          @order.update(coupon: @coupon)
          flash[:success] = 'Coupon code has been accepted'
        end
      else
        flash[:danger] = 'Coupon not found'
      end
    end

    def current_order
      @order = current_customer.order_in_progress
    end


    def order_params
      params.require(:orders).permit(:book_id, :quantity )
    end
  end
end

app/controllers/shop_cart/orders_controller.rb
require_dependency "shop_cart/application_controller"

module ShopCart
  class OrdersController < ApplicationController
    load_and_authorize_resource
    # GET /orders
    def index
      @orders = @orders.all_completed_orders
      @order = current_customer_order
      @order_items = @order.products

    end

    # GET /orders/1
    def show
      @order_items = @order.products
      @order_total = @order.total_price+@order.delivery_price
    end
  end
end

app/helpers/shop_cart/application_helper.rb
module ShopCart
  module ApplicationHelper
  end
end

app/views/shop_cart/order_items/index.html.erb
<div class="cart clearfix">
  <% unless @order_items.blank? %>
     <%= form_tag(update_all_order_items_path, :controller => 'order_items', action: :update_all, method: :put) do %>
        <table class="table table-condensed">
          <thead>
          <tr>
            <th colspan="2">BOOK</th>
            <th>PRICE</th>
            <th>QTY</th>
            <th>TOTAL</th>
            <th>&nbsp;</th>
          </tr>
          </thead>
          <tbody>
          <% @order_items.each do |item| %>
             <tr>
               <td><%= link_to(image_tag(item.product.image.thumb)) %></td>
               <td>
                 <div><%= item.product.title %></div>
                 <p><%= item.product.description %></p>
               </td>
               <td class="price"><%= number_to_currency(item.price) %></td>
               <td><%= number_field_tag('quantity['+item.id.to_s+']', item.quantity, {:min => 1, :max => 20, :class => 'form-control quantity'}) %></td>
               <td class="price"><%= number_to_currency(item.price*item.quantity) %></td>

               <td class="price remove"><%= link_to('&times;'.html_safe, url_for(action: :destroy, id: item.id), method: :delete) %></td>
             </tr>
          <% end %>
          </tbody>
        </table>
        <div class="clearfix">
          <div class="subtotal pull-right">SUBTOTAL: &nbsp; <strong>$<%= @order.total_price %></strong></div>
        </div>
        <div class="form-inline pull-right">
          <%= text_field_tag(:coupon, nil, placeholder: 'Coupon code',size: 12, class:"form-control") %>
          <%= submit_tag('UPDATE', :controller => 'order_items', :action => 'update',:method => 'put', :class => 'btn btn-default') %>
          <%= link_to('CHECKOUT', main_app.order_step_path(:address), :class => 'btn btn-default') %>
        </div>
        <%= link_to('EMPTY CART', destroy_all_order_items_path, {:class => 'btn btn-default', :method => 'delete'}) %>
        <%= link_to('CONTINUE SHOPPING', main_app.books_path, {:class => 'btn btn-default'}) %>
     <% end %>
  <% else %>
     <p>Shopping cart is empty... <%= link_to 'Get started shopping!', main_app.books_path %></p>
  <% end %>
</div>

app/views/shop_cart/orders/index.html.erb
<div class="orders clearfix">
  <h1>Orders</h1>
  <h2>In progress</h2>
  <% unless @order_items.blank? %>
     <div class="order">
       <%= render 'order_steps/order_details', order_items: @order_items %>
       <div class="clearfix">
         <div class="subtotal pull-right">SUBTOTAL: &nbsp; <strong><%= number_to_currency(@order.total_price) %></strong></div>
         <%= link_to 'GO TO CART', order_items_path, class: 'btn btn-default' %>
       </div>
     </div>
  <% else %>
     <p>Order is empty&hellip; <%= link_to 'Get started shopping!', main_app.books_path %></p>
  <% end %>
  <div>&nbsp;</div>
  <% unless (@orders.nil?) %>
     <% previous_state = '' %>
     <% @orders.each do |order| %>
        <% if previous_state != order.state %>
           <% if previous_state != '' %>
              </tbody>
              </table>
           <% end %>
           <h2><%= order.state.upcase %></h2>
           <table class="table table-condensed no-borders">
             <thead>
             <tr>
               <th width="40%">NUMBER</th>
               <th width="30%">COMPLETED&nbsp;AT</th>
               <th width="20%">TOTAL</th>
               <th width="10%">&nbsp;</th>
             </tr>
             </thead>
             <tbody>
        <%- end %>
        <tr>
          <td><%= order.number %></td>
          <td><%= date_format(order.completed_date) %></td>
          <td><%= number_to_currency(order.total_price+order.delivery_price) %></td>
          <td><%= link_to 'View', order_path(order) %></td>
        </tr>
        <% previous_state = order.state %>
     <% end %>
     </tbody>
     </table>
  <% end %>
</div>

app/views/shop_cart/orders/show.html.erb
<div class="clearfix">
  <div class="order-back"> <%= link_to '<< Back to orders', orders_path %></div>
  <h1 class="pull-left">Order <%= @order.number %></h1>
  <div class="order-status"> &nbsp; <%= @order.state %></div>
</div>
<div class="order clearfix">
  <% unless @order_items.blank? %>
     <%= render 'order_steps/order_details', order_items: @order_items %>
     <div class="clearfix">
       <div class="pull-right">
         <div class="subtotal clearfix">
           <div class="pull-right"><strong><%= number_to_currency(@order.total_price) %></strong><br /><strong><%= number_to_currency(@order.delivery_price) %></strong></div>
           <div class="pull-right">SUBTOTAL: &nbsp; <br />SHIPPING: &nbsp; </div>
         </div>
       </div>
     </div>
     <div class="clearfix total">
       <div class="pull-right subtotal">
         ORDER TOTAL: &nbsp; <strong><%= number_to_currency(@order_total) %></strong>
       </div>
     </div>
  <% else %>
     <p>Order is empty&hellip;</p>
  <% end %>
</div>